### ISSUE TITLE
TODO: DiscreteDP: Allow beta=1

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.py#242]
Re item 3 in https://github.com/QuantEcon/QuantEcon.py/issues/185#issue-106162601:

* [x] Let `DiscreteDP` accept `beta=1`
* [x] Disable `evaluate_policy`, `policy_iteration`, and `modified_policy_iteration` EDIT: and `value_iteration`: let them raise a `NotImplementedError` if `beta=1`
* [x] Update the docstring

Also write a notebook on Miranda-Fackler Section 7.6.6.
EDIT: Done by QuantEcon/QuantEcon.notebooks#37.
